### ISSUE TITLE
P2P Integration test randomly fail

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-elements#1103]
### Expected behavior
Integration test should be deterministic and not fail

### Actual behavior
Jenkins still fails at below
```
Integration tests for P2P library
Partially connected network which becomes fully connected: All nodes launch at the same time. The seedPeers list of each node contains the next node in the sequence. Discovery interval runs multiple times.
Peer discovery
should discover all peers in the network after a few cycles of discovery:
AssertionError: expected [ Array(9) ] to deeply equal [ Array(10) ]

at p2pNodeList.forEach.p2p (test/integration/p2p.ts:198:30)
at Array.forEach (<anonymous>)
at Context.it (test/integration/p2p.ts:192:17)
```

**Comment by shuse2** [comment]
Superseded by #1086
